### PR TITLE
Init package.json to make it a proper npm manifest

### PR DESCRIPTION
**Pull request by ydaniv**
We should also remove the `node_modules` directory completely and add it go `.gitignore`.
This update will let you run `> npm install`.

### CODE REVIEW

**Comment by vpontis** [comment]
Ok this seems great! I'll take a look at it tonight when I'm on my computer. (On phone now.)

So this will reproduce all of the stuff we have in node_modules when we do npm install?

**Comment by ydaniv** [comment]
Yes, it will install all packages with same version, or at least with same major and minor version.
Notice I put coffee-script dep in dev deps but it seems to be installed as well with `npm install`, but please double check me.

Now we can populate the rest of the fields in the manifest which I left clear (or with default text) and also add a `scripts` property with the commands we have in `server.sh`. Then we can do simply do `npm run` (if I'm not mistaken).

**Comment by willzeng** [comment]
Yep, we've need this for some time.  I won't be able to double check how it runs tonight, but @vpontis if you are able to then feel free to merge this change right in.

I'm down to replace using `server.sh` (which seems a bit ad hoc) with `npm run`.

**Comment by vpontis** [comment]
Yep, this seems good to me.

**Pull request merged**
