### PR TITLE
Initial docs generation infrastructure commit

### PR DESCRIPTION
**Pull request by ydaniv**

### CODE REVIEW

**Comment by vpontis** [comment]
Is the `index.html` file going to be automatically generated? If so, should we track it in Git?

**Comment by ydaniv** [comment]
@vpontis all the stuff inside `docs/` is automatically generated. That's a good question, usually I rather leave it untracked, but here I thought it would make it easier for non-devs to get it ready made. If you guys think it's redundant then we can remove that and put it in the .gitignore file

**Comment by vpontis** [comment]
I think it's much nicer having that stuff in `.gitignore` so we don't have to worry about committing it each time. We just need to make it easy enough to generate the docs that the non-devs can do it themselves. Or we could have one branch that doesn't have the `docs/` ignored. Would this fix that problem?

**Comment by ydaniv** [comment]
Let's try that
בתאריך 15 באפר 2014 18:58, "Victor Pontis" notifications@github.com כתב:

**Pull request merged**
