### PR TITLE
color and date display in nodeEdit

### PR DESCRIPTION
**Pull request by willzeng**

### CODE REVIEW

**Comment by vpontis** [comment]
This isn't working for me right now. It's just stuck trying to load on the homepage.

**Comment by vpontis** [comment]
Ah, it is because Celestrium code isn't there anymore. I'll try and pull that again and get it working.

**Comment by vpontis** [comment]
I tried to merge in dev but I'm not sure things are working as they should right now.

**Comment by willzeng** [comment]
Yeah the refactor merges a little strangely.  We can sort things tomorrow
all together.
-Z

**Pull request closed without merging**
