### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by willzeng**
@vpontis @backens @CalvinFong @tmad4000 

The easy thing to do it just to check out the new file structure in the github browser.  Thoughts about this as the structure for the code going forward?

### CODE REVIEW

**Comment by vpontis** [comment]
Yea, this looks great!

**Comment by willzeng** [comment]
Let's try to work off of this branch going forward if possible.  Will merge it into dev on Saturday.

**Comment by vpontis** [comment]
OK sweet. What are the issues with merging it to dev now? It says the pull request can be automatically merged.

**Comment by willzeng** [comment]
Just wanted to check that there weren't too many outstanding developments.  Since the files got moved around in the refactor there are still likely to be a few weird merge conflicts.  Should be good to go now though.

**Pull request merged**
