### PR TITLE
Create node popup

### PR DESCRIPTION
**Pull request by vpontis**
This pops up a modal so that it is easier to enter in longer descriptions for a node. 

Don't merge this yet. I'm just opening this issue so you can check it out and comment it. 

@willzeng @CalvinFong

### CODE REVIEW

**Comment by vpontis** [comment]
#80

**Comment by willzeng** [comment]
Looks good to me.  The only outstanding thing would be to replace the button that says popout with an appropriate icon.  [Take your pick](https://www.google.co.uk/search?q=pop+out+icon&safe=off&rlz=1C1CHFX_en-gbGB564GB565&espv=210&es_sm=93&source=lnms&tbm=isch&sa=X&ei=S6P4UoSkCNC20QWK_IHgDQ&ved=0CAkQ_AUoAQ&biw=1680&bih=949&dpr=1#q=pop+out+icon&safe=off&tbm=isch&tbs=isz:i&imgdii=_).

Any icon suggestions? @davidfurlong

**Comment by vpontis** [comment]
Check out font-awesome. I used [this icon](http://fortawesome.github.io/Font-Awesome/icon/expand/) for the popout.

**Comment by willzeng** [comment]
Looks rad to me.  For some reason the icon isn't showing up for me though, I'm just getting an empty icon placeholder.

Am unsure of what the bug is, but I assume it is working for you?

**Comment by vpontis** [comment]
Yea, I'll figure that out today then.

## 

VPontis

**Pull request merged**
